### ISSUE TITLE
Getting build error on Ubunut

### ISSUE THREAD

**Issue by johnlauer** [gorilla/websocket#22]
I'm getting the following error trying to build on Ubuntu 13.10
# github.com/gorilla/websocket

../../gorilla/websocket/client.go:167: undefined: net.Dialer

My build works fine on Windows. Is there something odd/different on Ubuntu?
